### ISSUE TITLE
default format for summary table

### ISSUE THREAD

**Issue by panavrin** [echo-lab/SensDat#11]
1. no NOT rows. 
 I think it would be better to NOT show the "NOT" rows in a summary table. 
It just confuses the users. Instead, it would be better to show the Dumping Zone summary only and make the rest expandable. You can add a button like "Expand In-between Summary". 

Also, it would be great to do a simple summary on the bottom 

2. Change the name Cycle to something else. I think Period may be a better term. Start Period from 1 from the time when the agent visits the dumping zone.  For example, the first column value is 1,2,3 but rather do 0,1,2. (Note that 0 will not be shown in the first place). 

![image](https://user-images.githubusercontent.com/605762/187830959-f68f47c1-144d-4be1-a2a1-400f2e4885ff.png)

3. Do a simple summary on the bottom 

Total Number of Periods
Average Total Time
Average Total Distance

**Comment by maneshd** [comment]
Completed w/ 6ee87469498cbf1173db0c27e31750f04517769e.

Note: the "total summary" table portion is associated w/ issue #20.
