### ISSUE TITLE
Adding a way to rotate/scale/translate the trajectory 

### ISSUE THREAD

**Issue by panavrin** [echo-lab/SensDat#13]
Based on the request from the construction team, we would like to allow users to import a background image, which can stand for a construction site's layout image. 

However, we cannot guarantee that the trajectory will perfectly align with the imported image. 

Therefore, the system should allow users to manipulate the trajectory to overlay the spatio-temporal trajectory on top of a site layout image. 

We expect three different manipulations: translate (drag and drop), rotate, and scale.

**Comment by maneshd** [comment]
Fixed by b30d781b451159b75dbcdb4633c944ced0ea5c8f
