### ISSUE TITLE
allowing a background image on the visualization graph

### ISSUE THREAD

**Issue by panavrin** [echo-lab/SensDat#14]
As mentioned in #13, we want to allow users to see a site layout image underneath the visualization. 

A user should be able to import an image that they create and import the image as a background. 

It should support image extensions. 

This indicates that the size of the map view may have to be in a fixed width-height, which would be dictated by the size of the image unless we scale the image. We probably do not want to distort the image in terms of width-height ratio, though.

**Comment by maneshd** [comment]
Fixed by b30d781b451159b75dbcdb4633c944ced0ea5c8f
