### ISSUE TITLE
Boundary Errors in Duration Calculation in Summary Table. 

### ISSUE THREAD

**Issue by panavrin** [echo-lab/SensDat#19]
<img width="1797" alt="image" src="https://user-images.githubusercontent.com/605762/192382516-0e1cf8fc-e268-4f9f-aa2b-d26c43d31832.png">

In calculating Total time, we simply subtract Start Time from End Time, which seems correct, but some errors are coming out of this calculation method. For example, if I want to calculate the cycle time (e.g., the time it takes for the truck to back to Region A), the first cycle time will be 15:24:11 (Start Time in Cycle 3) - 15:23:32 (Start Time in Cycle 2) which is 39 seconds. However, if we simply add the total time in Cylce 1, we get 37 seconds (1s + 36s).

In fact, the Total time for Region A Cycle 2 should be 2 seconds (15:23:32\~15:23:34), and Not REgion A cycle should be 37 seconds (15:23:34\~15:24:11) so that we calculate the total time not by the last timestamp within the state but by the first timestamp outside the state. 

 If we solve this, issue #5 will be resolved automatically btw

**Comment by maneshd** [comment]
Resolved w/ commit 62020401163587c3596071300a104d28d72242ad
