### ISSUE TITLE
Total summary table

### ISSUE THREAD

**Issue by panavrin** [echo-lab/SensDat#20]
I think we need another summary table that summarizes the entire state-related statistics (like GROUP BY [state name] ) 

The current table only summarizes the raw data per period (cycle). 

The total summary table should be placed ABOVE the current cycle-based summary table. 
In addition, it should include something like following 

* The total # of visits (A)
* The total duration (B)
* Average Duration per visit (B/A) 
* Total distance traveled within the state (D) 
* The total duration outside the state (C) 

Also, it should have the plus button like the other summary table so that users can calculate their own metrics. 

examples are 

a constant number that represent the bucket size times (A) tell us how much they delivered
(D) / (B) shows the speed.

**Comment by maneshd** [comment]
I took a first pass at this. Here's what it looks like so far:
<img width="400" alt="Screen Shot 2022-09-30 at 1 32 15 PM" src="https://user-images.githubusercontent.com/1320073/193325180-2c975d2e-8f6f-4410-bdb3-778ddc517a70.png">

What I think we might do in the future:

- Have separate rows for T/F values of the state. Whether we show just the T or both T&F can be tied to the same thing in the breakdown table
- When we hover over a value in the "Total" table, it should highlight the data used to calculate it in the "Breakdown" table
- We still need to implement the "+" button feature (both for "Total" and "Breakdown"). There's a bit still to figure out w/ the design there.

Maybe makes sense to open different issues for these things, but just wanted to write it down now before I forgot.

**Comment by maneshd** [comment]
(commit was: 486267808ee1b5b7daaa2ad18178aacfdcfff8c4)
