### ISSUE TITLE
Use only one date column

### ISSUE THREAD

**Issue by maneshd** [echo-lab/SensDat#21]
Use either original date format OR have original date on-hover for timestamps. Make sure that the text formatting is good (i.e., don't wrap text).

**Comment by maneshd** [comment]
I think you can keep a column in the data table but stop it from rendering by not returning the column [here](https://github.com/echo-lab/SensDat/blob/a8654106bb79ee343d4482a573dda0b355718086/src/data-table.js#L270)

For more context, looking at the table below, the column "Date Created" is just a string that was present in the original data, and the column "Time" comes from us parsing the Date Created column into a DateTime object and then formatting it a specific way. 
<img width="461" alt="Screen Shot 2022-10-24 at 10 16 07 AM" src="https://user-images.githubusercontent.com/1320073/197547706-3310c2a0-8ac9-418b-96bf-bf61b2d0a14d.png">

Personally, I think it would make sense to just drop the "Date Created" column.
After that, you could optionally do one of the following:
* Change the "Time" column to include the date, e.g., `11/11/2021 15:22:21`
* Change the "Time" column to include the date but only on-hover

**Comment by Andy1uu** [comment]
I am trying to work on dropping the Date Created Column right now but I am having some trouble with understanding how this table component you used renders its columns, is there documentation on this component?

**Comment by Andy1uu** [comment]
If you could give me some more clarification when you get the chance about how either filters operate with React or if there are other ways that I can make the Date Created Column not appear, I was experimenting with the CSS selector `display: none` but I would need to have a class that is dedicated to each row which I think we should talk about in a meeting before I move forward with that approach.

**Comment by maneshd** [comment]
So, the base table is rendered with the help of an external library. It's a little convoluted, but we tell it which columns we want to render [here](https://github.com/echo-lab/SensDat/blob/fb11db233343ab87d6612ea62ca4ff9ae0728204/src/data-view.js#L66) (the useTable() function later on is the function from the external library). The TL;DR: is that[ DataTable.getReactTableCols()](https://github.com/echo-lab/SensDat/blob/fb11db233343ab87d6612ea62ca4ff9ae0728204/src/data-table.js#L270) method will return a list of columns, and if the column in question isn't in the list, then it won't get rendered.

So: you need to filter one of the date columns out from that list of columns returned from getReactTableCols(). The "filter" isn't something React specific -- I just mean that you can use [Array.filter](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/filter) on the list.

**Comment by Andy1uu** [comment]
Closing this issue because it has been implemented.
