### ISSUE TITLE
make the header shorter if that's too long

### ISSUE THREAD

**Issue by panavrin** [echo-lab/SensDat#23]
so that the column is not too wide. (e.g., the average time in state is too wide even though that data is short)

**Comment by Andy1uu** [comment]
So it looks like the main issue for this is either the width that the title text box takes up, would you like me to decrease or set a static width and then make it so the text wraps instead?

**Comment by Andy1uu** [comment]
This is confusing sorry but I wanted to make sure the commits are separated out into different branches so I do not just keep iterating onto other issues that have not been approved yet. The most current one is the correct one, I have edited the widths for most of the columns except for the ones that are affected by other issues (Time, Date Created). Please look over the PR when you get the chance. Thank you.
