### ISSUE TITLE
enabling highlighting the visible data entries only when they are actually visible.  

### ISSUE THREAD

**Issue by panavrin** [echo-lab/SensDat#4]
<img width="1067" alt="image" src="https://user-images.githubusercontent.com/605762/187588254-fa113c39-f9e7-4967-b389-12d27bdc3f79.png">

When the table is not visible, highlighting data points that correspond to the visible rows in the table should be disabled. (cuz technically, the rows are not visible. For example, the picture above shows the step needed to create a compound state where the table is not visible anymore. However, there are still rows that are highlighted, which may confuse users.

**Comment by maneshd** [comment]
Fixed w/ 28bb77eea7a985119469c02a06577bbea0b031af
